"""empty message

Revision ID: 0cf26f94add7
Revises: fe2fe1e14343
Create Date: 2020-05-20 02:06:54.700197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf26f94add7'
down_revision = 'fe2fe1e14343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('firstname', sa.String(length=80), nullable=True))
    op.add_column('Users', sa.Column('lastname', sa.String(length=80), nullable=True))
    op.add_column('Users', sa.Column('photo', sa.String(length=255), nullable=True))
    op.drop_column('Users', 'profile_photo')
    op.drop_column('Users', 'last_name')
    op.drop_column('Users', 'first_name')
    op.drop_column('Users', 'joined_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('joined_on', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('Users', sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('Users', sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('Users', sa.Column('profile_photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('Users', 'photo')
    op.drop_column('Users', 'lastname')
    op.drop_column('Users', 'firstname')
    # ### end Alembic commands ###
